/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package managemusic;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aaron
 */
public class ManageMusicGUI extends JFrame {
    private Playlist likedPlaylist;
    private Playlist genre1Playlist;
    private Playlist genre2Playlist;
    private PlaylistManager playlistManager;

    //Constructor to initialize the GUI and create playlist objects.
    public ManageMusicGUI() {
        initComponents(); // Initialize GUI components
        likedPlaylist = new Playlist() {}; // Initialize liked playlist
        genre1Playlist = new Playlist() {}; // Initialize genre 1 playlist
        genre2Playlist = new Playlist() {}; // Initialize genre 2 playlist
        playlistManager = new PlaylistManager(); // Initialize playlist manager
    }

    //Updates the text area with the current content of all playlists
     private void updateTextArea() {
    StringBuilder sb = new StringBuilder();
    sb.append("Liked Playlist:\n");
    for (String song : likedPlaylist.getSongs()) {
        sb.append(song).append("\n");
    }
    sb.append("\nPop Playlist:\n");
    for (String song : genre1Playlist.getSongs()) {
        sb.append(song).append("\n");
    }
    sb.append("\nRap Playlist:\n");
    for (String song : genre2Playlist.getSongs()) {
        sb.append(song).append("\n");
    }
    // Append repeat playlist to the text area
    sb.append("\nRepeat Playlist:\n");
    for (String song : playlistManager.getRepeatPlaylist().getSongs()) {
        sb.append(song).append("\n");
    }
    TextArea.setText(sb.toString());
}
     
     
     private void addToRepeatPlaylist(String song) {
    // Adds the song to the repeat playlist
    playlistManager.addSongToRepeatPlaylist(song);
    // Updates the text area to display the repeat playlist
    updateTextArea();
}

    

//
public class PlaylistManager implements Repeatable {
    private boolean repeat;
    private Playlist repeatPlaylist;

    public PlaylistManager() {
        repeatPlaylist = new Playlist() {};
    }

    public void repeat() {
        repeat = !repeat; // Toggle repeat state
        System.out.println("Playlist repeat is " + (repeat ? "enabled" : "disabled"));
    }
    
    // Check if repeat mode is enabled.
    // True if repeat mode is enabled, false otherwise.
    public boolean isRepeatEnabled() {
        return repeat;
    }
    
    // Adds songs to the repeat playlsit
    public void addSongToRepeatPlaylist(String song) {
        repeatPlaylist.addSong(song);
    }
    
    // Gets the repeat playlist
    public Playlist getRepeatPlaylist() {
        return repeatPlaylist;
    }
}

private void repeatPlaylist() {
    // Create a new playlist with the songs from the liked playlist
    Playlist repeatedPlaylist = new Playlist() {};
    for (String song : likedPlaylist.getSongs()) {
        repeatedPlaylist.addSong(song);
    }
    // Update the text area with the repeated playlist
    StringBuilder sb = new StringBuilder();
    sb.append("Repeated Playlist:\n");
    for (String song : repeatedPlaylist.getSongs()) {
        sb.append(song).append("\n");
    }
    TextArea.setText(sb.toString());
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genre1Btn = new javax.swing.JButton();
        Genre2Btn = new javax.swing.JButton();
        LikedBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        SongTf = new javax.swing.JTextField();
        SongLbl = new javax.swing.JLabel();
        MoveBtn = new javax.swing.JButton();
        RepeatBtn = new javax.swing.JButton();
        DisplayBtn = new javax.swing.JButton();
        TitleLbl = new javax.swing.JLabel();
        GenreLbl = new javax.swing.JLabel();
        MoveLikedBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        BackgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Genre1Btn.setText("Pop");
        Genre1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Genre1BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Genre1Btn);
        Genre1Btn.setBounds(310, 230, 72, 23);

        Genre2Btn.setText("Rap");
        Genre2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Genre2BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Genre2Btn);
        Genre2Btn.setBounds(390, 230, 72, 23);

        LikedBtn.setText("Add to liked");
        LikedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LikedBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LikedBtn);
        LikedBtn.setBounds(48, 270, 120, 23);

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBtn);
        DeleteBtn.setBounds(28, 56, 100, 23);

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBtn);
        SearchBtn.setBounds(28, 97, 100, 23);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        ScrollPane.setViewportView(TextArea);

        getContentPane().add(ScrollPane);
        ScrollPane.setBounds(140, 60, 305, 153);

        SongTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SongTfActionPerformed(evt);
            }
        });
        getContentPane().add(SongTf);
        SongTf.setBounds(139, 227, 71, 22);

        SongLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SongLbl.setForeground(new java.awt.Color(255, 255, 255));
        SongLbl.setText("Enter song name:");
        getContentPane().add(SongLbl);
        SongLbl.setBounds(28, 230, 99, 16);

        MoveBtn.setText("Move");
        MoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(MoveBtn);
        MoveBtn.setBounds(28, 145, 100, 23);

        RepeatBtn.setText("Repeat Playlist");
        RepeatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeatBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RepeatBtn);
        RepeatBtn.setBounds(340, 270, 120, 23);

        DisplayBtn.setText("Display number of songs per playlist");
        DisplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayBtn);
        DisplayBtn.setBounds(111, 305, 280, 23);

        TitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("Manage Your Music");
        getContentPane().add(TitleLbl);
        TitleLbl.setBounds(180, 20, 169, 25);

        GenreLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GenreLbl.setForeground(new java.awt.Color(255, 255, 255));
        GenreLbl.setText("Select genre:");
        getContentPane().add(GenreLbl);
        GenreLbl.setBounds(224, 230, 73, 16);

        MoveLikedBtn.setText("Move from liked");
        MoveLikedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveLikedBtnActionPerformed(evt);
            }
        });
        getContentPane().add(MoveLikedBtn);
        MoveLikedBtn.setBounds(190, 270, 130, 23);

        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewBtn);
        ViewBtn.setBounds(28, 186, 100, 23);

        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managemusic/Screenshot 2024-03-16 182422.png"))); // NOI18N
        getContentPane().add(BackgroundLbl);
        BackgroundLbl.setBounds(-3, -4, 510, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SongTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SongTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SongTfActionPerformed

    private void LikedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LikedBtnActionPerformed
        // TODO add your handling code here:
         // Get the song name
    String song = SongTf.getText().trim();
    
    // Check if the song name is empty
    if (song.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a song name.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if song name is empty
    }
    
    // Add the song to the liked playlist
    likedPlaylist.addSong(song);
    
    // Update the text area to reflect the changes
    updateTextArea();
    
    }//GEN-LAST:event_LikedBtnActionPerformed

    private void MoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveBtnActionPerformed
        // TODO add your handling code here:
        // Get the song name from the text field
    String song = SongTf.getText().trim();

    // Check if the song name is empty
    if (song.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a song name.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if song name is empty
    }

    // Check if the song exists in either genre1Playlist or genre2Playlist
    boolean songExistsInGenre1 = genre1Playlist.contains(song);
    boolean songExistsInGenre2 = genre2Playlist.contains(song);

    // If the song doesn't exist in either playlist, show an error message
    if (!songExistsInGenre1 && !songExistsInGenre2) {
        JOptionPane.showMessageDialog(this, "The song '" + song + "' does not exist in any playlist.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Prompt the user to select the destination playlist
    String[] playlists = {"Pop Playlist", "Rap Playlist"};
    String selectedPlaylist = (String) JOptionPane.showInputDialog(this, "Select playlist to move the song to:",
            "Select Playlist", JOptionPane.QUESTION_MESSAGE, null, playlists, playlists[0]);

    // Check if user canceled the operation
    if (selectedPlaylist == null) {
        JOptionPane.showMessageDialog(this, "Operation canceled by the user.", "Canceled", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Remove the song from the old playlist and add it to the new playlist
    if (selectedPlaylist.equals("Pop Playlist")) {
        if (songExistsInGenre2) {
            // Remove the song from genre2Playlist
            genre2Playlist.removeSong(song);
        }
        // Add the song to genre1Playlist
        genre1Playlist.addSong(song);
    } else if (selectedPlaylist.equals("Rap Playlist")) {
        if (songExistsInGenre1) {
            // Remove the song from genre1Playlist
            genre1Playlist.removeSong(song);
        }
        // Add the song to genre2Playlist
        genre2Playlist.addSong(song);
    }

    // Update the text area to reflect the changes
    updateTextArea();
    }//GEN-LAST:event_MoveBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
         // Get the song name
    String song = SongTf.getText().trim();

    // Check if the song name is empty
    if (song.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a song name.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if song name is empty
    }

    // Prompt the user to select a playlist
    String[] playlists = {"Liked Playlist", "Pop Playlist", "Rap Playlist", "Repeat Playlist"};
    String selectedPlaylist = (String) JOptionPane.showInputDialog(this, "Select playlist to delete the song from:",
            "Select Playlist", JOptionPane.QUESTION_MESSAGE, null, playlists, playlists[0]);

    // Check if user canceled the operation
    if (selectedPlaylist == null) {
        JOptionPane.showMessageDialog(this, "Operation canceled by the user.", "Canceled", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Delete the song from the selected playlist
    switch (selectedPlaylist) {
        case "Liked Playlist":
            if (!likedPlaylist.contains(song)) {
                JOptionPane.showMessageDialog(this, "The song '" + song + "' does not exist in the Liked Playlist.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            likedPlaylist.removeSong(song);
            break;
        case "Pop Playlist":
            if (!genre1Playlist.contains(song)) {
                JOptionPane.showMessageDialog(this, "The song '" + song + "' does not exist in the Pop Playlist.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            genre1Playlist.removeSong(song);
            break;
        case "Rap Playlist":
            if (!genre2Playlist.contains(song)) {
                JOptionPane.showMessageDialog(this, "The song '" + song + "' does not exist in the Rap Playlist.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            genre2Playlist.removeSong(song);
            break;
        case "Repeat Playlist":
            if (!playlistManager.getRepeatPlaylist().contains(song)) {
                JOptionPane.showMessageDialog(this, "The song '" + song + "' does not exist in the Repeat Playlist.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            playlistManager.getRepeatPlaylist().removeSong(song);
            break;
        default:
            JOptionPane.showMessageDialog(this, "Invalid playlist selected.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Update the text area
    updateTextArea();


    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
     // Get the search query from the text field
    String searchQuery = SongTf.getText();
    
    // Call the search method and set the result in the text area
    String result = searchSong(searchQuery);
    TextArea.setText(result);
}

// Method to search for a song in all playlists
private String searchSong(String songName) {
    // Initialize a StringBuilder to store the search result
    StringBuilder result = new StringBuilder();
    
    // Initialize a boolean flag to track if the song is found
    boolean found = false;
    
    // Search for the song in each playlist and update the result accordingly
    if (likedPlaylist.contains(songName)) {
        result.append(songName).append(" found in Liked Playlist\n");
        found = true;
    }
    if (genre1Playlist.contains(songName)) {
        result.append(songName).append(" found in Pop Playlist\n");
        found = true;
    }
    if (genre2Playlist.contains(songName)) {
        result.append(songName).append(" found in Rap Playlist\n");
        found = true;
    }
    if (playlistManager.getRepeatPlaylist().contains(songName)) {
        result.append(songName).append(" found in Repeat Playlist\n");
        found = true;
    }
    
    // If the song is not found in any playlist, indicate so in the result
    if (!found) {
        result.append("Song not found in any playlist!\n");
    }
    
    // Return the search result as a string
    return result.toString();

    }//GEN-LAST:event_SearchBtnActionPerformed

    private void Genre2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Genre2BtnActionPerformed
        // TODO add your handling code here:
        // Get the song name from the text field
    String song = SongTf.getText().trim();
    
    // Check if the song name is empty
    if (song.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a song name.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if song name is empty
    }
    
    // Add song to genre 2 playlist
    genre2Playlist.addSong(song);
    
    // Update the text area
    updateTextArea();
    }//GEN-LAST:event_Genre2BtnActionPerformed

    private void Genre1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Genre1BtnActionPerformed
        // TODO add your handling code here:
         String song = SongTf.getText().trim();
    
    // Check if the song name is empty
    if (song.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a song name.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if song name is empty
    }
    
    // Add song to genre 1 playlist
    genre1Playlist.addSong(song);
    
    // Update the text area
    updateTextArea();
    }//GEN-LAST:event_Genre1BtnActionPerformed

    private void RepeatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeatBtnActionPerformed
        // TODO add your handling code here:
        // Get the song name from the text field
    String song = SongTf.getText().trim();
    
    // Check if the song name is empty
    if (song.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a song name.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if song name is empty
    }
    
    // Call the method to add the song to the repeat playlist
    addToRepeatPlaylist(song);

    }//GEN-LAST:event_RepeatBtnActionPerformed

    private void DisplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBtnActionPerformed
        // TODO add your handling code here:                                           
    // Call the method to display the number of songs per playlist
    displayNumberOfSongs();
}                                          

// Method to display the number of songs per playlist
private void displayNumberOfSongs() {
    // Get the number of songs in each playlist
    int likedCount = likedPlaylist.getSongs().size();
    int genre1Count = genre1Playlist.getSongs().size();
    int genre2Count = genre2Playlist.getSongs().size();
    int repeatCount = playlistManager.getRepeatPlaylist().getSongs().size();
    
    // Prepare the text to display in the text area
    StringBuilder sb = new StringBuilder();
    sb.append("Number of songs in Liked Playlist: ").append(likedCount).append("\n");
    sb.append("Number of songs in Pop Playlist: ").append(genre1Count).append("\n");
    sb.append("Number of songs in Rap Playlist: ").append(genre2Count).append("\n");
    sb.append("Number of songs in Repeat Playlist: ").append(repeatCount).append("\n");
    
    // Set the text in the text area to display the counts
    TextArea.setText(sb.toString());
    }//GEN-LAST:event_DisplayBtnActionPerformed

    private void MoveLikedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveLikedBtnActionPerformed
        // TODO add your handling code here:
        // Get the last song added to the Liked Playlist
    List<String> likedSongs = likedPlaylist.getSongs();
    if (likedSongs.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Liked Playlist is empty.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String song = likedSongs.get(likedSongs.size() - 1); // Get the last song

    // Prompt the user to select the destination playlist
    String[] playlists = {"Pop Playlist", "Rap Playlist"};
    String selectedPlaylist = (String) JOptionPane.showInputDialog(this, "Select playlist to move the song to:",
            "Select Playlist", JOptionPane.QUESTION_MESSAGE, null, playlists, playlists[0]);

    // Check if user canceled the operation
    if (selectedPlaylist == null) {
        JOptionPane.showMessageDialog(this, "Operation canceled by the user.", "Canceled", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Remove the song from the Liked Playlist and add it to the selected playlist
    likedPlaylist.removeSong(song);
    if (selectedPlaylist.equals("Pop Playlist")) {
        genre1Playlist.addSong(song);
    } else if (selectedPlaylist.equals("Rap Playlist")) {
        genre2Playlist.addSong(song);
    }

    // Update the text area to reflect the changes
    updateTextArea();
    }//GEN-LAST:event_MoveLikedBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        // Prompt the user to select a playlist
    String[] playlists = {"Liked Playlist", "Pop Playlist", "Rap Playlist", "Repeat Playlist"};
    String selectedPlaylist = (String) JOptionPane.showInputDialog(this, "Select playlist to view songs:",
            "Select Playlist", JOptionPane.QUESTION_MESSAGE, null, playlists, playlists[0]);

    // Check if user canceled the operation
    if (selectedPlaylist == null) {
        JOptionPane.showMessageDialog(this, "Operation canceled by the user.", "Canceled", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Get the songs from the selected playlist and display them in the text area
    String playlistContent = getSongsFromPlaylist(selectedPlaylist);
    TextArea.setText(playlistContent);
    }//GEN-LAST:event_ViewBtnActionPerformed

    // Method to get songs from the selected playlist
private String getSongsFromPlaylist(String playlistName) {
    Playlist selectedPlaylist = null;
    switch (playlistName) {
        case "Liked Playlist":
            selectedPlaylist = likedPlaylist;
            break;
        case "Pop Playlist":
            selectedPlaylist = genre1Playlist;
            break;
        case "Rap Playlist":
            selectedPlaylist = genre2Playlist;
            break;
        case "Repeat Playlist":
            selectedPlaylist = playlistManager.getRepeatPlaylist();
            break;
        default:
            // This should not happen, but if it does, return an empty string
            return "";
    }

    List<String> songs = selectedPlaylist.getSongs();
    if (songs.isEmpty()) {
        return "There are no songs in this playlist.";
    } else {
        StringBuilder playlistContent = new StringBuilder();
        for (String song : songs) {
            playlistContent.append(song).append("\n");
        }
        return playlistContent.toString();
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMusicGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton DisplayBtn;
    private javax.swing.JButton Genre1Btn;
    private javax.swing.JButton Genre2Btn;
    private javax.swing.JLabel GenreLbl;
    private javax.swing.JButton LikedBtn;
    private javax.swing.JButton MoveBtn;
    private javax.swing.JButton MoveLikedBtn;
    private javax.swing.JButton RepeatBtn;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel SongLbl;
    private javax.swing.JTextField SongTf;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JButton ViewBtn;
    // End of variables declaration//GEN-END:variables
}
